[package]
name = "seracca"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.3.2"
tera = "1.10.0"
pulldown-cmark = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.2"